//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Setting
    {
        public int ID { get; set; }
        public Nullable<int> Element_ID { get; set; }
        public Nullable<int> Control_ID { get; set; }
        public string Setting_Name { get; set; }
    
        public virtual Control_Account Control_Account { get; set; }
        public virtual Element_Account Element_Account { get; set; }
    }
}
