//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advance
    {
        public int Advance_ID { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public Nullable<double> Advance_Amount { get; set; }
        public string Status { get; set; }
        public System.DateTime Advance_Period { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
