//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer_Commision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dealer_Commision()
        {
            this.Dealer_Commision_Detail = new HashSet<Dealer_Commision_Detail>();
        }
    
        public int ID { get; set; }
        public int Member_id { get; set; }
        public Nullable<int> Dealer_ID { get; set; }
        public Nullable<double> Percentage { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dealer_Commision_Detail> Dealer_Commision_Detail { get; set; }
        public virtual Member Member { get; set; }
    }
}
