//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dealer()
        {
            this.Dealer_Commision = new HashSet<Dealer_Commision>();
            this.Dealer1 = new HashSet<Dealer>();
            this.Ledger_Account = new HashSet<Ledger_Account>();
        }
    
        public int Dealer_ID { get; set; }
        public string Company_Name { get; set; }
        public string Company_Phone { get; set; }
        public string Company_Address { get; set; }
        public string Contact_Person_Name { get; set; }
        public string Person_Phone { get; set; }
        public string Person_Email { get; set; }
        public string Person_CNIC { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<double> Percentage { get; set; }
        public string Reg_No { get; set; }
        public System.DateTime Reg_Date { get; set; }
        public Nullable<int> ParentDealerId { get; set; }
        public string Addressbanker { get; set; }
        public string PartyName1 { get; set; }
        public string PartyName2 { get; set; }
        public string YearOfEstablished { get; set; }
        public string CEOName { get; set; }
        public string CEOCNIC { get; set; }
        public string CEOQualification { get; set; }
        public string ResidentialAddress { get; set; }
        public string Telephone { get; set; }
        public string NTN { get; set; }
        public Nullable<double> DealerOfficePrice { get; set; }
        public Nullable<double> DealerAppartmentPrice { get; set; }
        public Nullable<double> DealerShopPrice { get; set; }
        public Nullable<double> DealerPentHousePrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dealer_Commision> Dealer_Commision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dealer> Dealer1 { get; set; }
        public virtual Dealer Dealer2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ledger_Account> Ledger_Account { get; set; }
    }
}
