//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer_Commision_Detail
    {
        public int ID { get; set; }
        public Nullable<int> Dealer_Commsion_ID { get; set; }
        public Nullable<double> Percentage { get; set; }
        public Nullable<bool> Status { get; set; }
        public System.DateTime Due_date { get; set; }
        public Nullable<System.DateTime> Pay_date { get; set; }
        public double Due_Amount { get; set; }
        public string Name { get; set; }
    
        public virtual Dealer_Commision Dealer_Commision { get; set; }
    }
}
