//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Development_Charges
    {
        public int ID { get; set; }
        public double Amount { get; set; }
        public System.DateTime Paid_Date { get; set; }
        public Nullable<int> Payment_ID { get; set; }
        public string Narration { get; set; }
        public Nullable<int> Head { get; set; }
        public string receipt_No { get; set; }
    
        public virtual Payment_Plan Payment_Plan { get; set; }
    }
}
