//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dummy
    {
        public int RV_ID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> Payment_ID { get; set; }
        public string Manual_Voucher_Number { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
    
        public virtual reciept_vouchers reciept_vouchers { get; set; }
    }
}
