//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Advances = new HashSet<Advance>();
            this.Attendences = new HashSet<Attendence>();
            this.Loans = new HashSet<Loan>();
            this.Members = new HashSet<Member>();
            this.OverTimes = new HashSet<OverTime>();
            this.Party_Detail = new HashSet<Party_Detail>();
            this.PayRoles = new HashSet<PayRole>();
            this.Salary_With_Allowences = new HashSet<Salary_With_Allowences>();
        }
    
        public int Employee_ID { get; set; }
        public string F_Name { get; set; }
        public string L_Name { get; set; }
        public string Designation { get; set; }
        public string Phone_Number { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime Joining_Date { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Martial_Status { get; set; }
        public Nullable<bool> Status { get; set; }
        public byte[] Profile_Picture { get; set; }
        public string CNIC { get; set; }
        public string Shift { get; set; }
        public string Password { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advance> Advances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendence> Attendences { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan> Loans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OverTime> OverTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Party_Detail> Party_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayRole> PayRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salary_With_Allowences> Salary_With_Allowences { get; set; }
    }
}
