//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Final_
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> Manual_Voucher_No { get; set; }
        public string Reg_No { get; set; }
        public string Name { get; set; }
        public string Cheque_No { get; set; }
        public Nullable<double> MCB_Islamic { get; set; }
        public Nullable<double> Meezan_Bank { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> Prsnl_A_C { get; set; }
    }
}
