//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment_Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Installment_Plan()
        {
            this.Plots = new HashSet<Plot>();
        }
    
        public int ID { get; set; }
        public Nullable<double> Booking { get; set; }
        public Nullable<double> Allocation { get; set; }
        public Nullable<double> Confirmation { get; set; }
        public Nullable<double> Monthly { get; set; }
        public Nullable<double> Half_Yearly { get; set; }
        public Nullable<int> No_Of_Monthly { get; set; }
        public Nullable<int> No_Of_Half_Yearly { get; set; }
        public Nullable<double> Pocession { get; set; }
        public string Plan_Name { get; set; }
        public Nullable<bool> Scheme { get; set; }
        public Nullable<double> Total_Price { get; set; }
        public string Plot_Type { get; set; }
        public Nullable<double> Quatlerly_installment { get; set; }
        public Nullable<int> NoOfQuaterly { get; set; }
        public Nullable<double> yearly { get; set; }
        public Nullable<int> NoOfYearly { get; set; }
        public string Size { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plot> Plots { get; set; }
    }
}
