//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Installment()
        {
            this.Sub_Installment = new HashSet<Sub_Installment>();
        }
    
        public int Installment_ID { get; set; }
        public Nullable<double> Single_Monthly_Installment { get; set; }
        public Nullable<double> Single_Half_Yearly_Installment { get; set; }
        public Nullable<int> Installment_No { get; set; }
        public System.DateTime Payment_Month { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<int> Payment_ID { get; set; }
        public Nullable<int> no_of_half_yearly_installments { get; set; }
        public Nullable<int> no_of_monthly_installments { get; set; }
        public Nullable<double> Amount_Paid { get; set; }
        public Nullable<System.DateTime> Paid_Month { get; set; }
        public byte[] Image { get; set; }
        public string Comment { get; set; }
        public Nullable<double> Monthly_Paid { get; set; }
        public Nullable<int> no_of_quaterly_installments { get; set; }
        public Nullable<int> no_of_yearly_installments { get; set; }
        public Nullable<double> Single_quaterly_Installment { get; set; }
        public Nullable<double> Single_yearly_Installment { get; set; }
    
        public virtual Payment_Plan Payment_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sub_Installment> Sub_Installment { get; set; }
    }
}
