//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lakeViewNewDbEntities3 : DbContext
    {
        public lakeViewNewDbEntities3()
            : base("name=lakeViewNewDbEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_Setting> Account_Setting { get; set; }
        public virtual DbSet<Advance> Advances { get; set; }
        public virtual DbSet<Attendence> Attendences { get; set; }
        public virtual DbSet<Control_Account> Control_Account { get; set; }
        public virtual DbSet<Dealer> Dealers { get; set; }
        public virtual DbSet<Dealer_Commision> Dealer_Commision { get; set; }
        public virtual DbSet<Dealer_Commision_Detail> Dealer_Commision_Detail { get; set; }
        public virtual DbSet<dealer_data> dealer_data { get; set; }
        public virtual DbSet<Development_Charges> Development_Charges { get; set; }
        public virtual DbSet<Dummy> Dummies { get; set; }
        public virtual DbSet<Element_Account> Element_Account { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<File_Transfer> File_Transfer { get; set; }
        public virtual DbSet<Final_> Final_ { get; set; }
        public virtual DbSet<Installment_Plan> Installment_Plan { get; set; }
        public virtual DbSet<Installment> Installments { get; set; }
        public virtual DbSet<Ledger_Account> Ledger_Account { get; set; }
        public virtual DbSet<Loan> Loans { get; set; }
        public virtual DbSet<Loan_Installments> Loan_Installments { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<memberImage> memberImages { get; set; }
        public virtual DbSet<MemberShipFee> MemberShipFees { get; set; }
        public virtual DbSet<C_Members_Record__> C_Members_Record__ { get; set; }
        public virtual DbSet<C_Members_Record__A> C_Members_Record__A { get; set; }
        public virtual DbSet<newPlot> newPlots { get; set; }
        public virtual DbSet<old_member_record_2> old_member_record_2 { get; set; }
        public virtual DbSet<old_member_record_3> old_member_record_3 { get; set; }
        public virtual DbSet<old_voucher_2> old_voucher_2 { get; set; }
        public virtual DbSet<old_member_record> old_member_record { get; set; }
        public virtual DbSet<old_voucher> old_voucher { get; set; }
        public virtual DbSet<OpenFile> OpenFiles { get; set; }
        public virtual DbSet<Oversea> Overseas { get; set; }
        public virtual DbSet<OverTime> OverTimes { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<Party_Detail> Party_Detail { get; set; }
        public virtual DbSet<payment_DAta> payment_DAta { get; set; }
        public virtual DbSet<Payment_Plan> Payment_Plan { get; set; }
        public virtual DbSet<Payment_Transfer> Payment_Transfer { get; set; }
        public virtual DbSet<paymentVoucher> paymentVouchers { get; set; }
        public virtual DbSet<PayRole> PayRoles { get; set; }
        public virtual DbSet<Plot> Plots { get; set; }
        public virtual DbSet<Plot_History> Plot_History { get; set; }
        public virtual DbSet<reciept_voucher_payment> reciept_voucher_payment { get; set; }
        public virtual DbSet<reciept_vouchers> reciept_vouchers { get; set; }
        public virtual DbSet<Refund> Refunds { get; set; }
        public virtual DbSet<Role_Permission> Role_Permission { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<Salary_With_Allowences> Salary_With_Allowences { get; set; }
        public virtual DbSet<Sheet1_> Sheet1_ { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Sub_Installment> Sub_Installment { get; set; }
        public virtual DbSet<SurchargePercentage> SurchargePercentages { get; set; }
        public virtual DbSet<ThumbScan> ThumbScans { get; set; }
        public virtual DbSet<update_record> update_record { get; set; }
    }
}
