//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ledger_Account()
        {
            this.reciept_voucher_payment = new HashSet<reciept_voucher_payment>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Ledger_Account_Code { get; set; }
        public string Ledger_Complete_Code { get; set; }
        public string Ledger_Account_Title { get; set; }
        public Nullable<int> Element_Account_Code { get; set; }
        public Nullable<int> Control_Account_Code { get; set; }
        public string Sub_Ledger_Account_Code { get; set; }
        public string Sub_Ledger_Account_Title { get; set; }
        public string Element_Account_Title { get; set; }
        public string Control_Account_Title { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<int> Element_ID { get; set; }
        public Nullable<int> Control_ID { get; set; }
        public Nullable<int> Member_ID { get; set; }
        public Nullable<int> Dealer_ID { get; set; }
    
        public virtual Control_Account Control_Account { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual Element_Account Element_Account { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reciept_voucher_payment> reciept_voucher_payment { get; set; }
    }
}
