//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Installments
    {
        public int Installment_ID { get; set; }
        public Nullable<int> Loan_ID { get; set; }
        public Nullable<int> Installment_Number { get; set; }
        public string IsPaid { get; set; }
        public System.DateTime Payment_Month { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual Loan Loan { get; set; }
    }
}
