//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan()
        {
            this.Loan_Installments = new HashSet<Loan_Installments>();
        }
    
        public int Loan_ID { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public Nullable<double> Loan_Amount { get; set; }
        public Nullable<int> No_Of_Installments { get; set; }
        public Nullable<double> Single_Installment_Amount { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan_Installments> Loan_Installments { get; set; }
    }
}
