//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class newPlot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public newPlot()
        {
            this.Plots = new HashSet<Plot>();
        }
    
        public int Id { get; set; }
        public string PlotNo { get; set; }
        public string Block { get; set; }
        public string Street { get; set; }
        public Nullable<bool> isAssigned { get; set; }
        public string plotType { get; set; }
        public string specialType { get; set; }
        public string wide { get; set; }
        public string reg_no { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plot> Plots { get; set; }
    }
}
