//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class old_voucher
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Old_V_Number { get; set; }
        public string Ledger_Account { get; set; }
        public string Member_Name { get; set; }
        public Nullable<double> Reg_No { get; set; }
        public string Narration { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
