//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class old_member_record_2
    {
        public int ID { get; set; }
        public Nullable<int> Reg_No { get; set; }
        public string Block { get; set; }
        public string Street { get; set; }
        public string Size { get; set; }
        public string Category { get; set; }
        public string Member_Name { get; set; }
        public string CNIC { get; set; }
        public string SO_DO_WO { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<double> Plot_Price { get; set; }
        public string Plan { get; set; }
        public string Dealer_Name { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
    }
}
