//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenFile
    {
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<double> Sr { get; set; }
        public string Type { get; set; }
        public Nullable<double> PBNo { get; set; }
        public string Size { get; set; }
        public string Dealer { get; set; }
        public string ReIssued { get; set; }
        public string Status { get; set; }
        public Nullable<double> RefNo { get; set; }
        public string Closer { get; set; }
        public string RateofFile { get; set; }
        public string RateMatured { get; set; }
        public Nullable<double> Balance { get; set; }
        public int Id { get; set; }
    }
}
