//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oversea
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string SoDoWo { get; set; }
        public string CNICOrPassport { get; set; }
        public string Email { get; set; }
        public string SecondaryContact { get; set; }
        public string Contact { get; set; }
        public string Country { get; set; }
        public string OverseasAddress { get; set; }
        public string pakistanAddress { get; set; }
        public string KinName { get; set; }
        public string KinSoDoWo { get; set; }
        public string kinCNIC { get; set; }
        public string KinContact { get; set; }
        public string ReferenceNo { get; set; }
        public string Size { get; set; }
        public System.DateTime Date { get; set; }
        public byte[] profileImage { get; set; }
    }
}
