//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverTime
    {
        public int Over_Time_ID { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public Nullable<double> No_Of_Hours { get; set; }
        public Nullable<double> Rate_Per_Hour { get; set; }
        public System.DateTime Month { get; set; }
        public Nullable<double> Total_Amount { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
