//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party_Detail
    {
        public int ID { get; set; }
        public Nullable<int> Party_ID { get; set; }
        public System.DateTime Pay_Date { get; set; }
        public Nullable<double> Current_Amount { get; set; }
        public Nullable<double> Previous_Amount { get; set; }
        public string Head { get; set; }
        public string Receipt_No { get; set; }
        public string Check_No { get; set; }
        public Nullable<bool> voucher_check { get; set; }
        public string Manual_Voucher_No { get; set; }
        public string transferFromBank { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Party Party { get; set; }
    }
}
