//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentVoucher
    {
        public int Id { get; set; }
        public System.DateTime date { get; set; }
        public string appNo { get; set; }
        public double amount { get; set; }
        public string checkPoDD { get; set; }
        public string drawnOn { get; set; }
        public double totalbalance { get; set; }
        public Nullable<int> paymentId { get; set; }
        public string VoucherNo { get; set; }
        public string onAccount { get; set; }
    
        public virtual Payment_Plan Payment_Plan { get; set; }
    }
}
