//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Transfer
    {
        public int ID { get; set; }
        public string From_EB { get; set; }
        public string To_EB { get; set; }
        public Nullable<double> Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string Prefix { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    }
}
