//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayRole
    {
        public int PayRole_ID { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public System.DateTime Period { get; set; }
        public Nullable<double> Net_Salary { get; set; }
        public Nullable<double> Gross_Salary { get; set; }
        public Nullable<int> Salary_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
