//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plot()
        {
            this.Payment_Plan = new HashSet<Payment_Plan>();
            this.Plot_History = new HashSet<Plot_History>();
        }
    
        public int Plot_ID { get; set; }
        public Nullable<int> Member_ID { get; set; }
        public string Reg_No { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Plot_No { get; set; }
        public Nullable<int> Size { get; set; }
        public string Street { get; set; }
        public string Block { get; set; }
        public string Plot_Type { get; set; }
        public string Plot_No_Sub { get; set; }
        public string irregular_size { get; set; }
        public string prefix { get; set; }
        public string Qm_No { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> length { get; set; }
        public string societyname { get; set; }
        public string sector { get; set; }
    
        public virtual Installment_Plan Installment_Plan { get; set; }
        public virtual Member Member { get; set; }
        public virtual newPlot newPlot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment_Plan> Payment_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plot_History> Plot_History { get; set; }
    }
}
