//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class reciept_vouchers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reciept_vouchers()
        {
            this.reciept_voucher_payment = new HashSet<reciept_voucher_payment>();
        }
    
        public int RV_ID { get; set; }
        public string Type { get; set; }
        public int VoucherNum { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string Manual_Voucher_No { get; set; }
        public string Drown_bank { get; set; }
        public Nullable<byte> IsChecked { get; set; }
        public Nullable<byte> IsApproved { get; set; }
        public byte[] Image { get; set; }
        public string Comments { get; set; }
        public string Prefix { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
    
        public virtual Dummy Dummy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reciept_voucher_payment> reciept_voucher_payment { get; set; }
        public virtual reciept_vouchers reciept_vouchers1 { get; set; }
        public virtual reciept_vouchers reciept_vouchers2 { get; set; }
    }
}
