//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class reciept_voucher_payment
    {
        public int RVP_ID { get; set; }
        public Nullable<int> RV_ID { get; set; }
        public string TransType { get; set; }
        public Nullable<int> Element_Account_Code { get; set; }
        public Nullable<int> Control_Account_Code { get; set; }
        public Nullable<int> Ledger_Account_Code { get; set; }
        public string Comments { get; set; }
        public double Amount { get; set; }
        public Nullable<double> PreviousBalance { get; set; }
        public Nullable<double> CurrentBalance { get; set; }
        public Nullable<int> Ledger_ID { get; set; }
    
        public virtual Ledger_Account Ledger_Account { get; set; }
        public virtual reciept_vouchers reciept_vouchers { get; set; }
    }
}
