//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refund
    {
        public int ID { get; set; }
        public string Member_Name { get; set; }
        public string Reg_No { get; set; }
        public System.DateTime Date { get; set; }
        public double Amount { get; set; }
        public string Head { get; set; }
        public string Narration { get; set; }
        public string Receipt_no { get; set; }
        public string father_name { get; set; }
        public string Size { get; set; }
        public string CNIC { get; set; }
        public string Plot_type { get; set; }
        public string Ledger_Type { get; set; }
    }
}
