//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Permission
    {
        public int Roles_Permission_ID { get; set; }
        public Nullable<int> Roles_ID { get; set; }
        public string Module_Key { get; set; }
        public Nullable<bool> Target { get; set; }
    
        public virtual role role { get; set; }
    }
}
