//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary_With_Allowences
    {
        public int Salary_ID { get; set; }
        public Nullable<double> Basic_Salary { get; set; }
        public Nullable<double> Convance_Allownce { get; set; }
        public Nullable<double> House_Rent_Allowence { get; set; }
        public Nullable<double> Medical_Allowence { get; set; }
        public Nullable<double> Rate_Per_Hour { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public Nullable<double> Gross_Salary { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
