//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Society.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Installment
    {
        public int ID { get; set; }
        public Nullable<int> Installment_ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Receipt_No { get; set; }
        public string Manual_Receipt_No { get; set; }
    
        public virtual Installment Installment { get; set; }
    }
}
